version: "3.1"

services:

  app:
    container_name: app
    restart: unless-stopped
    env_file: ../.env
    build:
      context: ../
      dockerfile: ./.dockers/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../src:/app/src

  app_db:
    image: postgres:15.2
    container_name: app_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
      TZ: America/Hermosillo
    volumes:
      - ../DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app_adminer:
    image: adminer
    container_name: app_adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8080:8080
    depends_on:
      app_db:
        condition: service_started